# conda env create --file environment.yml
# mamba env create --file environment.yml
name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - plotly
  - seaborn
  - python={{ cookiecutter.python_version }}
  {% if cookiecutter.project_packages == "All" -%}
  - keras
  - lightgbm
  - pandas-flavor
  - pandas-profiling
  - pylint
  - pyspark
  - scikit-learn
  - statsmodels
  - tensorflow
  {% endif -%}
  